development:
  adapter: postgresql
  database: sample_app_development
  encoding: unicode
  user: sample_app
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: sample_app_test
  encoding: unicode
  user: sample_app
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sample_app_production
  encoding: unicode
  pool: 5
  timeout: 5000